/**
 * hexagram.js
 * @IExplanation(name = "Hexagram",
description="Enumeration representing the Hexagrams BaGua in Fu Xi Sequence Binary Order i.e. Ascending Binary Value with rightmost digit = LSB (least significant bit)" +
			"When drawing the hexagram, the order of righting to the console forces a reversal in the order the hexagram is rendered. as read from bottom up" +
			"Mapping of binary to king wen sequence: http://www.biroco.com/yijing/sequence.htm")
@IReference(title = "A Companion To Yi Jing Numerology and Cosmology", "https://en.wikibooks.org/wiki/I_Ching/Explanation_Of_I_Ching_Hexagrams_And_Lines"
author= "Nielsen, B",
date= "2003",
publisher = "Element",
page ="3",
description = "Usage: The PRIMARY naming of the hexagrams as enumerations and the placing of hexagrams into palaces."
			+ " - Duplicate Names: When a hexgram name is in common between 2 different Hexagrams, the first occurrence of the Hexgram"
			+ "    in binary terms is CAPITALISED, unless the conflict involves a hexagram named after its two inner trigrams which bear the same name. "
			+ "    in which case it is CAPITALISED as in the case of QIAN (qian, qian)"
			+ " - If a name consists of two words, an underscore separates the words.")
 */
import bagua from '@/const/bagua';

const hexagram = {
    kūn: {
        name: 'kūn',
        symbol: '坤', 
        hexagram: '䷁',
        binary: '000000',
        order: 0, 
        kingwen:2, 
        translation: 'The Receptive',  
        summary: `Receptive energy, nurturing, and yielding. This hexagram symbolizes openness, patience, and the willingness to follow rather than lead. It advises embracing humility and allowing things to unfold naturally`,
        above: bagua.bagua.kūn,
        below: bagua.bagua.kūn,
    },
    bō: {
        name: 'bō',
        symbol: '剝', 
        hexagram: '䷖',
        binary: '100000',
        order: 1, 
        kingwen:23,  
        translation: 'Splitting Apart',         
        summary: `This hexagram symbolizes the need to let go of what no longer serves you. It advises you to release old patterns and beliefs that are holding you back and to make space for new growth and opportunities.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.kūn,
    },
    bǐ: {
        name: 'bǐ',
        symbol: '比', 
        hexagram: '䷇',
        binary: '010000',
        order: 2, 
        kingwen:8,        
        translation: 'Holding Together (Union)', 
        summary: `This hexagram symbolizes the need to work together and cooperate with others. It advises you to put aside your differences and focus on what you have in common.`,  
        above: bagua.bagua.kǎn,
        below: bagua.bagua.kūn,
    },
    guān: {
        name: 'guān',
        symbol: '觀', 
        hexagram: '䷓',
        binary: '110000',
        order: 3, 
        kingwen:20,        
        translation: 'Contemplation (View)', 
        summary: `This hexagram symbolizes the need to take a step back and observe. It advises you to take a detached view of the situation and to consider the bigger picture before making a decision.`,  
        above: bagua.bagua.xùn,
        below: bagua.bagua.kūn,
    },
    yù: {
        name: 'yù',
        symbol: '豫', 
        hexagram: '䷏',
        binary: '001000',
        order: 4,   
        kingwen:16, 
        translation: 'Enthusiasm', 
        summary: `This hexagram symbolizes the need to approach life with enthusiasm and optimism. It advises you to embrace new opportunities and to pursue your goals with passion and energy.`,              
        above: bagua.bagua.zhèn,
        below: bagua.bagua.kūn,
    },
    jìn: {
        name: 'jìn',
        symbol: '晉', 
        hexagram: '䷢',
        binary: '101000',
        order: 5, 
        kingwen:35,        
        translation: 'Progress',   
        summary: `This hexagram symbolizes progress and growth. It advises you to keep moving forward and to stay focused on your goals. It encourages you to take action and to keep pushing yourself`,
        above: bagua.bagua.lí,
        below: bagua.bagua.kūn,
    },
    cui: {
        name: 'cui',
        symbol: '萃', 
        hexagram: '䷬',
        binary: '011000',
        order: 6,   
        kingwen:45,      
        translation: 'Gathering Together',   
        summary: `This hexagram symbolizes the power of coming together as a group. It advises you to work with others and to combine your strengths to achieve your goals. It encourages you to collaborate and cooperate with those around you.`,
        above: bagua.bagua.duì,
        below: bagua.bagua.kūn,
    },
    pǐ: {
        name: 'pǐ',
        symbol: '否', 
        hexagram: '䷋',
        binary: '111000',
        order: 7,
        kingwen:12,
        translation: 'Standstill (Stagnation)',            
        summary: `This hexagram symbolizes a period of stagnation and lack of progress. It advises you to be patient and to wait for the right time to act. It encourages you to take a step back and to reevaluate your goals and priorities`,
        above: bagua.bagua.qián,
        below: bagua.bagua.kūn,
    },
    qiān: {
        name: 'qiān',
        symbol: '謙', 
        hexagram: '䷎',
        binary: '000100',
        order: 8,   
        kingwen:15,   
        translation: 'Modesty',      
        summary: `This hexagram symbolizes the power of humility and modesty. It advises you to approach life with an open mind and a willingness to learn from others. It encourages you to be humble and to treat others with respect.`,
        above: bagua.bagua.kūn,
        below: bagua.bagua.gèn,
    },
    gèn: {
        name: 'gèn',
        symbol: '艮', 
        hexagram: '䷳',
        binary: '100100',
        order: 9,   
        kingwen:52,  
        translation: ' Keeping Still, Mountain',       
        summary: `This hexagram symbolizes the power of stillness and stability. It advises you to be patient and to stay grounded in the face of challenges. It encourages you to stand firm in your beliefs and to remain true to yourself.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.gèn,
    },
    jiǎn: {
        name: 'jiǎn',
        symbol: '蹇', 
        hexagram: '䷦',
        binary: '010100',
        order: 10,
        kingwen:39,         
        translation: 'Chien / Obstruction',   
        summary: `This hexagram symbolizes the power of overcoming obstacles and challenges. It advises you to face your fears and to push through difficulties. It encourages you to stay focused on your goals and to keep moving forward.`,
        above: bagua.bagua.kǎn,
        below: bagua.bagua.gèn,
    },
    jiàn: {
        name: 'jiàn',
        symbol: '漸', 
        hexagram: '䷴',
        binary: '110100',
        order: 11, 
        kingwen:53,  
        translation: 'Development (Gradual Progress)', 
        summary: `This hexagram symbolizes the power of gradual progress and growth. It advises you to take small steps towards your goals and to be patient with yourself. It encourages you to focus on the journey rather than the destination.`,          
        above: bagua.bagua.xùn,
        below: bagua.bagua.gèn,
    },
    xiǎoguò: {
        name: 'xiǎo guò',
        symbol: '小過', 
        hexagram: '䷽',
        binary: '001100',
        order: 12, 
        kingwen:62, 
        translation: 'Preponderance of the Small', 
        summary: `This hexagram symbolizes the power of small actions and incremental changes. It advises you to pay attention to the details and to take small steps towards your goals. It encourages you to be patient and to trust that your efforts will pay off in the long run.`,        
        above: bagua.bagua.zhèn,
        below: bagua.bagua.gèn,
    },
    lǚ: {
        name: 'lǚ',
        symbol: '旅', 
        hexagram: '䷷',
        binary: '101100',
        order: 13,  
        kingwen:56, 
        translation: 'The Wanderer',       
        summary: `This hexagram symbolizes the power of exploration and discovery. It advises you to embrace new experiences and to step outside of your comfort zone. It encourages you to be open to new opportunities and to follow your curiosity.`,  
        above: bagua.bagua.zhèn,
        below: bagua.bagua.gèn,
    },
    xián: {
        name: 'xián',
        symbol: '咸', 
        hexagram: '䷞',
        binary: '011100',
        order: 14, 
        kingwen:31,     
        translation: 'Influence (Wooing)',     
        summary: `This hexagram symbolizes the power of attraction and influence. It advises you to be mindful of the impact you have on others and to use your influence wisely. It encourages you to build strong connections and to foster harmonious relationships.`,
        above: bagua.bagua.duì,
        below: bagua.bagua.gèn,
    },
    dùn: {
        name: 'dùn',
        symbol: '遯', 
        hexagram: '䷠',
        binary: '111100',
        order: 15,
        kingwen:33,    
        translation: 'Retreat',     
        summary: `This hexagram symbolizes the power of retreat and withdrawal. It advises you to take a step back and to create space for reflection and introspection. It encourages you to listen to your inner voice and to trust your intuition.`,   
        above: bagua.bagua.qián,
        below: bagua.bagua.gèn,
    },
    shī: {
        name: 'shī',
        symbol: '師', 
        hexagram: '䷆',   
        binary: '000010',     
        order: 16, 
        kingwen:7,  
        translation: 'The Army',    
        summary: `This hexagram symbolizes the power of leadership and strategy. It advises you to take charge and to lead with confidence. It encourages you to be decisive and to trust your instincts.`,     
        above: bagua.bagua.kūn,
        below: bagua.bagua.kǎn,
    },
    méng: {
        name: 'méng',
        symbol: '蒙', 
        hexagram: '䷃',
        binary: '100010',
        order: 17,    
        kingwen:4,   
        translation: 'Youthful Folly',     
        summary: `This hexagram symbolizes the power of innocence and curiosity. It advises you to embrace your inner child and to approach life with a sense of wonder and playfulness. It encourages you to be open to new experiences and to learn from your mistakes.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.kǎn,
    },
    kǎn: {
        name: 'kǎn',
        symbol: '坎', 
        hexagram: '䷜',
        binary: '010010',
        order: 18,
        kingwen:29,   
        translation: 'The Abysmal (Water)',         
        summary: `This hexagram symbolizes the power of the unknown and the unconscious. It advises you to trust your intuition and to explore your emotions. It encourages you to dive deep into your subconscious and to uncover hidden truths.`,
        above: bagua.bagua.kǎn,
        below: bagua.bagua.kǎn,
    },
    huàn: {
        name: 'huàn',
        symbol: '渙', 
        hexagram: '䷺',
        binary: '110010',
        order: 19,
        kingwen:59,     
        translation: 'Dispersion (Dissolution)',       
        summary: `This hexagram symbolizes the power of release and letting go. It advises you to surrender to the flow of life and to release what no longer serves you. It encourages you to trust the process and to allow things to unfold naturally.`,
        above: bagua.bagua.xùn,
        below: bagua.bagua.kǎn,
    },
    xiè: {
        name: 'xiè',
        symbol: '解', 
        hexagram: '䷧',
        binary: '001010',
        order: 20, 
        kingwen:40,      
        translation: 'Deliverance',     
        summary: `This hexagram symbolizes the power of liberation and freedom. It advises you to break free from the past and to embrace new opportunities. It encourages you to let go of what is holding you back and to step into your power.`,
        above: bagua.bagua.zhèn,
        below: bagua.bagua.kǎn,
    },
    wèijì: {
        name: 'wèi jì',
        symbol: '未濟', 
        hexagram: '䷿',
        binary: '101010',
        order: 21,
        kingwen:64,    
        translation: 'Before Completion',      
        summary: `This hexagram symbolizes the power of unfinished business and incomplete projects. It advises you to tie up loose ends and to complete what you have started. It encourages you to stay focused and to follow through on your commitments.`,  
        above: bagua.bagua.lí,
        below: bagua.bagua.kǎn,
    },
    kùn: {
        name: 'kùn',
        symbol: '困', 
        hexagram: '䷮',
        binary: '011010',
        order: 22,  
        kingwen:47,       
        translation: 'Oppression (Exhaustion)',   
        summary: `This hexagram symbolizes the power of oppression and exhaustion. It advises you to take a break and to rest and recharge. It encourages you to listen to your body and to take care of yourself.`,
        above: bagua.bagua.duì,
        below: bagua.bagua.kǎn,
    },
    sòng: {
        name: 'sòng',
        symbol: '訟', 
        hexagram: '䷅',
        binary: '111010',
        order: 23, 
        kingwen:6,   
        translation: 'Conflict',     
        summary: `This hexagram symbolizes the power of conflict and disagreement. It advises you to address the issues at hand and to find a resolution. It encourages you to communicate openly and honestly with others.`,    
        above: bagua.bagua.qián,
        below: bagua.bagua.kǎn,
    },
    shēng: {
        name: 'shēng',
        symbol: '升', 
        hexagram: '䷭',
        binary: '000110',
        order: 24,  
        kingwen:46,  
        translation: 'Pushing Upward',   
        summary: `This hexagram symbolizes the power of growth and expansion. It advises you to reach for the stars and to pursue your dreams with passion and determination. It encourages you to step out of your comfort zone and to embrace new opportunities.`,     
        above: bagua.bagua.kūn,
        below: bagua.bagua.xùn,
    },
    gǔ: {
        name: 'gǔ',
        symbol: '蠱', 
        hexagram: '䷑',
        binary: '100110',
        order: 25, 
        kingwen:18,   
        translation: 'Work on What Has Been Spoiled (Decay)',        
        summary: `This hexagram symbolizes the power of transformation and renewal. It advises you to let go of what no longer serves you and to make space for new growth and opportunities. It encourages you to embrace change and to trust the process.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.xùn,
    },
    jǐng: {
        name: 'jǐng',
        symbol: '井', 
        hexagram: '䷯',
        binary: '010110',
        order: 26, 
        kingwen:48,      
        translation: 'Ching / The Well',     
        summary: `This hexagram symbolizes the power of nourishment and sustenance. It advises you to take care of yourself and to nurture your body, mind, and spirit. It encourages you to prioritize your well-being and to make self-care a priority.`,
        above: bagua.bagua.kǎn,
        below: bagua.bagua.xùn,
    },
    xùn: {
        name: 'xùn',
        symbol: '巽', 
        hexagram: '䷸',
        binary: '110110',
        order: 27,    
        kingwen:57,     
        translation: 'The Gentle (Penetrating, Wind)',   
        summary: `This hexagram symbolizes the power of flexibility and adaptability. It advises you to go with the flow and to embrace change with an open mind. It encourages you to be open to new ideas and to be willing to try new things.`,
        above: bagua.bagua.xùn,
        below: bagua.bagua.xùn,
    },
    héng: {
        name: 'héng',
        symbol: '恆', 
        hexagram: '䷟',
        binary: '001110',
        order: 28, 
        kingwen:32,      
        translation: 'Duration',     
        summary: `This hexagram symbolizes the power of endurance and perseverance. It advises you to stay the course and to keep moving forward, even in the face of challenges. It encourages you to trust the process and to stay focused on your goals.`,
        above: bagua.bagua.zhèn,
        below: bagua.bagua.xùn,
    },
    dǐng: {
        name: 'dǐng',
        symbol: '鼎', 
        hexagram: '䷱',
        binary: '101110',
        order: 29, 
        kingwen:50,    
        translation: 'The Caldron',  
        summary: `This hexagram symbolizes the power of transformation and change. It advises you to embrace new opportunities and to let go of what no longer serves you. It encourages you to trust the process and to be open to new possibilities.`,     
        above: bagua.bagua.lí,
        below: bagua.bagua.xùn,
    },
    dàguò: {
        name: 'dà guò',
        symbol: '大過', 
        hexagram: '䷛',
        binary: '011110',
        order: 30, 
        kingwen:28,    
        translation: 'Preponderance of the Great',    
        summary: `This hexagram symbolizes the power of excess and overindulgence. It advises you to be mindful of your actions and to avoid going to extremes. It encourages you to find balance in all areas of your life and to practice moderation.`,   
        above: bagua.bagua.duì,
        below: bagua.bagua.xùn,
    },
    gòu: {
        name: 'gòu',
        symbol: '姤', 
        hexagram: '䷫',
        binary: '111110',
        order: 31,
        kingwen:44,     
        translation: 'Coming to Meet',     
        summary: `This hexagram symbolizes the power of connection and collaboration. It advises you to work together with others and to build strong relationships. It encourages you to be open to new opportunities and to embrace the power of community.`,  
        above: bagua.bagua.qián,
        below: bagua.bagua.xùn,
    },
    fù: {
        name: 'fù',
        symbol: '復', 
        hexagram: '䷗',
        binary: '000001',
        order: 32,  
        kingwen:24, 
        translation: 'Return (The Turning Point)',    
        summary: `This hexagram symbolizes the power of transformation and change. It advises you to let go of the past and to embrace new opportunities. It encourages you to trust the process and to be open to new possibilities.`,          
        above: bagua.bagua.kūn,
        below: bagua.bagua.zhèn,
    },
    yí: {
        name: 'yí',
        symbol: '頤', 
        hexagram: '䷚',
        binary: '100001',
        order: 33,   
        kingwen:27,   
        translation: 'Corners of the Mouth (Nourishment)',   
        summary: `This hexagram symbolizes the power of nourishment and self-care. It advises you to take care of yourself and to prioritize your well-being. It encourages you to nourish your body, mind, and spirit and to make self-care a priority.`,     
        above: bagua.bagua.gèn,
        below: bagua.bagua.zhèn,
    },
    zhūn: {
        name: 'zhūn',
        symbol: '屯', 
        hexagram: '䷂',
        binary: '010001',
        order: 34,   
        kingwen:3,  
        translation: 'Difficulty at the Beginning',   
        summary: `This hexagram symbolizes the power of challenges and obstacles. It advises you to stay the course and to keep moving forward, even in the face of difficulties. It encourages you to trust the process and to be patient with yourself.
        This hexagram represents a period of struggle where obstacles appear daunting, but perseverance and careful planning can lead to growth and eventual success.`,      
        above: bagua.bagua.kǎn,
        below: bagua.bagua.zhèn,
    },
    yì: {
        name: 'yì',
        symbol: '益', 
        hexagram: '䷩',
        binary: '110001',
        order: 35,   
        kingwen:42,    
        translation: 'Increase',  
        summary: `This hexagram symbolizes the power of growth and expansion. It advises you to embrace new opportunities and to pursue your goals with passion and determination. It encourages you to take action and to keep pushing yourself.`,     
        above: bagua.bagua.xùn,
        below: bagua.bagua.zhèn,
    },
    zhèn: {
        name: 'zhèn',
        symbol: '震', 
        hexagram: '䷲',
        binary: '001001',
        order: 36,   
        kingwen:51,  
        translation: 'The Arousing (Shock, Thunder)',  
        summary: `This hexagram symbolizes the power of awakening and transformation. It advises you to embrace change and to step into your power. It encourages you to trust the process and to be open to new possibilities.`,       
        above: bagua.bagua.zhèn,
        below: bagua.bagua.zhèn,
    },
    shìkè: {
        name: 'shì kè',
        symbol: '噬嗑', 
        hexagram: '䷔',
        binary: '101001',
        order: 37,   
        kingwen:21,   
        translation: 'Biting Through',   
        summary: `This hexagram symbolizes the power of determination and perseverance. It advises you to stay focused on your goals and to push through obstacles. It encourages you to be resilient and to keep moving forward, even in the face of challenges.`,     
        above: bagua.bagua.lí,
        below: bagua.bagua.zhèn,
    },
    suí: {
        name: 'suí',
        symbol: '隨', 
        hexagram: '䷐',
        binary: '011001',
        order: 38,   
        kingwen:17,  
        translation: 'Following',  
        summary: `This hexagram symbolizes the power of following and surrendering. It advises you to go with the flow and to trust the process. It encourages you to be open to new opportunities and to embrace the power of surrender.`,       
        above: bagua.bagua.duì,
        below: bagua.bagua.zhèn,
    },
    wúwàng: {
        name: 'wú wàng',
        symbol: '無妄', 
        hexagram: '䷘',
        binary: '111001',
        order: 39,   
        kingwen:25,       
        translation: 'Innocence (The Unexpected)', 
        summary: `This hexagram symbolizes the power of innocence and spontaneity. It advises you to approach life with an open mind and a sense of wonder. It encourages you to be open to new experiences and to embrace the unexpected.`,   
        above: bagua.bagua.qián,
        below: bagua.bagua.zhèn,
    },
    míngyí: {
        name: 'míng yí',
        symbol: '明夷', 
        hexagram: '䷣',
        binary: '000101',
        order: 40,   
        kingwen:36,   
        translation: 'Darkening of the Light', 
        summary: `This hexagram symbolizes the power of darkness and uncertainty. It advises you to trust the process and to be patient with yourself. It encourages you to embrace the unknown and to trust that the light will return.`,       
        above: bagua.bagua.kūn,
        below: bagua.bagua.lí,
    },
    bì: {
        name: 'bì',
        symbol: '賁', 
        hexagram: '䷕',
        binary: '100101',
        order: 41,   
        kingwen:22,  
        translation: 'Grace',         
        summary: `This hexagram symbolizes the power of grace and beauty. It advises you to embrace your inner beauty and to let your light shine. It encourages you to be kind to yourself and to others and to cultivate a sense of grace and elegance.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.lí,
    },
    jìjì: {
        name: 'jì jì',
        symbol: '既濟', 
        hexagram: '䷾',
        binary: '010101',
        order: 42,   
        kingwen:63,  
        translation: 'After Completion',         
        summary: `This hexagram symbolizes the power of completion and fulfillment. It advises you to celebrate your achievements and to take pride in your accomplishments. It encourages you to take a moment to reflect on how far you have come and to savor the moment.`,
        above: bagua.bagua.kǎn,
        below: bagua.bagua.lí,
    },
    jiārén: {
        name: 'jiā rén',
        symbol: '家人', 
        hexagram: '䷤',
        binary: '110101',
        order: 43,   
        kingwen:37,  
        translation: 'The Family (The Clan)',         
        summary: `This hexagram symbolizes the power of family and community. It advises you to nurture your relationships and to build strong connections with those around you. It encourages you to support and care for one another and to create a sense of belonging`,
        above: bagua.bagua.xùn,
        below: bagua.bagua.lí,
    },
    fēng: {
        name: 'fēng',
        symbol: '豐', 
        hexagram: '䷶',
        binary: '001101',
        order: 44,   
        kingwen:55,  
        translation: 'Abundance',  
        summary: `This hexagram symbolizes the power of abundance and prosperity. It advises you to be grateful for what you have and to share your blessings with others. It encourages you to cultivate a sense of abundance and to trust that there is enough for everyone.`,       
        above: bagua.bagua.zhèn,
        below: bagua.bagua.lí,
    },
    lí: {
        name: 'lí',
        symbol: '離', 
        hexagram: '䷝',
        binary: '101101',
        order: 45,   
        kingwen:30,   
        translation: 'The Clinging, Fire',        
        summary: `This hexagram symbolizes the power of passion and desire. It advises you to follow your heart and to pursue your dreams with passion and determination. It encourages you to be bold and to take risks in pursuit of your goals.`,
        above: bagua.bagua.lí,
        below: bagua.bagua.lí,
    },
    gé: {
        name: 'gé',
        symbol: '革', 
        hexagram: '䷰',
        binary: '011101',
        order: 46,   
        kingwen:49,    
        translation: 'Revolution (Molting)',      
        summary: `This hexagram symbolizes the power of transformation and change. It advises you to let go of what no longer serves you and to embrace new opportunities. It encourages you to trust the process and to be open to new possibilities.`, 
        above: bagua.bagua.duì,
        below: bagua.bagua.lí,
    },
    tóngrén: {
        name: 'tóng rén',
        symbol: '同人', 
        hexagram: '䷌',
        binary: '111101',
        order: 47,   
        kingwen:13,  
        translation: 'Fellowship with Men',   
        summary: `This hexagram symbolizes the power of connection and community. It advises you to work together with others and to build strong relationships. It encourages you to support and care for one another and to create a sense of belonging.`,      
        above: bagua.bagua.qián,
        below: bagua.bagua.lí,
    },
    lín: {
        name: 'lín',
        symbol: '臨', 
        hexagram: '䷒',
        binary: '000011',
        order: 48,   
        kingwen:19,   
        translation: 'Approach', 
        summary: `This hexagram symbolizes the power of preparation and planning. It advises you to take a step back and to consider your options before making a decision. It encourages you to approach the situation with an open mind and to be prepared for what lies ahead.`,       
        above: bagua.bagua.kūn,
        below: bagua.bagua.duì,
    },
    sǔn: {
        name: 'sǔn',
        symbol: '損', 
        hexagram: '䷨',
        binary: '100011',
        order: 49,   
        kingwen:41,  
        translation: 'Decrease',         
        summary: `This hexagram symbolizes the power of loss and sacrifice. It advises you to let go of what no longer serves you and to make space for new growth and opportunities. It encourages you to release old patterns and beliefs that are holding you back.`,
        above: bagua.bagua.gèn,
        below: bagua.bagua.duì,
    },
    jié: {
        name: 'jié',
        symbol: '節', 
        hexagram: '䷻',
        binary: '010011',
        order: 50,   
        kingwen:60,        
        translation: 'Limitation',   
        summary: `This hexagram symbolizes the power of boundaries and limitations. It advises you to set clear boundaries and to honor your own needs and desires. It encourages you to take care of yourself and to prioritize your well-being.`,
        above: bagua.bagua.kǎn,
        below: bagua.bagua.duì,
    },
    zhōngfú: {
        name: 'zhōng fú',
        symbol: '中孚', 
        hexagram: '䷼',
        binary: '110011',
        order: 51,   
        kingwen:61,
        translation: 'Inner Truth',           
        summary: `This hexagram symbolizes the power of inner truth and authenticity. It advises you to listen to your inner voice and to trust your intuition. It encourages you to be true to yourself and to follow your heart.`,
        above: bagua.bagua.xùn,
        below: bagua.bagua.duì,
    },
    guīmèi: {
        name: 'guī mèi',
        symbol: '歸妹', 
        hexagram: '䷵',
        binary: '001011',
        order: 52,   
        kingwen:54,        
        translation: 'The Marrying Maiden',   
        summary: `This hexagram symbolizes the power of union and partnership. It advises you to work together with others and to build strong relationships. It encourages you to support and care for one another and to create a sense of belonging.`,
        above: bagua.bagua.zhèn,
        below: bagua.bagua.duì,        
    },
    kuí: {
        name: 'kuí',
        symbol: '睽', 
        hexagram: '䷥',
        binary: '101011',
        order: 53,   
        kingwen:38,        
        translation: 'Opposition',  
        summary: `This hexagram symbolizes the power of opposition and conflict. It advises you to address the issues at hand and to find a resolution. It encourages you to communicate openly and honestly with others.`, 
        above: bagua.bagua.lí,
        below: bagua.bagua.duì,
    },
    duì: {
        name: 'duì',
        symbol: '兌', 
        hexagram: '䷹',
        binary: '011011',  
        order: 54,   
        kingwen:58,        
        translation: 'The Joyous, Lake',   
        summary: `This hexagram symbolizes the power of joy and celebration. It advises you to embrace the present moment and to find joy in the little things. It encourages you to celebrate your successes and to share your happiness with others.`,
        above: bagua.bagua.duì,
        below: bagua.bagua.duì,        
    },
    lu: {
        name: 'lu',
        symbol: '履', 
        hexagram: '䷉',
        binary: '111011', 
        order: 55,   
        kingwen:10,        
        translation: 'Treading (Conduct)',   
        summary: `This hexagram symbolizes the power of action and movement. It advises you to take the first step and to move forward with confidence. It encourages you to trust the process and to be open to new opportunities.`,
        above: bagua.bagua.qián,
        below: bagua.bagua.duì,       
    },
    tài: {
        name: 'tài',
        symbol: '泰', 
        hexagram: '䷊',
        binary: '000111', 
        order: 56,   
        kingwen:11,  
        translation: 'Peace',       
        summary: `This hexagram symbolizes the power of peace and harmony. It advises you to find balance in all areas of your life and to cultivate a sense of inner peace. It encourages you to create a sense of calm and tranquility in your surroundings.`,  
        above: bagua.bagua.kūn,
        below: bagua.bagua.qián,        
    },
    dàchù: {
        name: 'dà chù',
        symbol: '大畜', 
        hexagram: '䷙',
        binary: '100111', 
        order: 57,   
        kingwen:26,   
        translation: 'The Taming Power of the Great',        
        summary: `This hexagram symbolizes the power of discipline and self-control. It advises you to stay focused on your goals and to be patient with yourself. It encourages you to trust the process and to be open to new possibilities.`, 
        above: bagua.bagua.gèn,
        below: bagua.bagua.qián,        
    },
    xū: {
        name: 'xū',
        symbol: '需', 
        hexagram: '䷄',
        binary: '010111', 
        order: 58,   
        kingwen:5,
        translation: 'Waiting (Nourishment)',    
        summary: `This hexagram symbolizes the power of patience and waiting. It advises you to trust the process and to be patient with yourself. It encourages you to take a step back and to allow things to unfold naturally.`,      
        above: bagua.bagua.kǎn,
        below: bagua.bagua.qián,        
    },
    xiǎochù: {
        name: 'xiǎo chù',
        symbol: '小畜', 
        hexagram: '䷈',
        binary: '110111', 
        order: 59,   
        kingwen:9,  
        translation: 'The Taming Power of the Small', 
        summary: `This hexagram symbolizes the power of discipline and self-control. It advises you to stay focused on your goals and to be patient with yourself. It encourages you to trust the process and to be open to new possibilities.`,        
        above: bagua.bagua.xùn,
        below: bagua.bagua.qián,        
    },
    dàzhuàng: {
        name: 'dà zhuàng',
        symbol: '大壯', 
        hexagram: '䷡',
        binary: '001111', 
        order: 60,   
        kingwen:34,   
        translation: 'The Power of the Great',  
        summary: `This hexagram symbolizes the power of strength and vitality. It advises you to embrace your inner power and to step into your full potential. It encourages you to be bold and to take risks in pursuit of your goals.`,      
        above: bagua.bagua.zhèn,
        below: bagua.bagua.qián,        
    },
    dàyǒu: {
        name: 'dà yǒu',
        symbol: '大有', 
        hexagram: '䷍',
        binary: '101111', 
        order: 61,   
        kingwen:14,    
        translation: 'Possession in Great Measure',  
        summary: `This hexagram symbolizes the power of abundance and prosperity. It advises you to be grateful for what you have and to share your blessings with others. It encourages you to cultivate a sense of abundance and to trust that there is enough for everyone.`,     
        above: bagua.bagua.lí,
        below: bagua.bagua.qián,        
    },
    guài: {
        name: 'guài',
        symbol: '夬', 
        hexagram: '䷪',
        binary: '011111',
        order: 62,   
        kingwen:43,      
        translation: 'Break-through (Resoluteness)',  
        summary: `This hexagram symbolizes the power of breakthrough and transformation. It advises you to break free from the past and to embrace new opportunities. It encourages you to trust the process and to be open to new possibilities.`,   
        above: bagua.bagua.duì,
        below: bagua.bagua.qián,      
    },
    qián: {
        name: 'qián',
        symbol: '乾', 
        hexagram: '䷀',
        binary: '111111',
        order: 63,   
        kingwen:1,    
        translation: 'The Creative, Heaven',
        summary: `This hexagram symbolizes the power of creation and new beginnings. It advises you to embrace your inner power and to step into your full potential. It encourages you to be bold and to take risks in pursuit of your goals. 
        </br> This hexagram represents active energy, initiative, and the force to bring new ideas into reality. It signifies a time of dynamic progress and leadership.`,
        above: bagua.bagua.qián,
        below: bagua.bagua.qián,
        explanation: `The first hexagram is made up of six unbroken lines. These unbroken lines stand for the primal power, which is light-giving, active, strong, and of the spirit. The hexagram is consistently strong in character, and since it is without weakness, its essence is power or energy. Its image is heaven. Its energy is represented as unrestricted by any fixed conditions in space and is therefore conceived of as motion. Time is regarded as the basis of this motion. Thus the hexagram includes also the power of time and the power of persisting in time, that is, duration. The power represented by the hexagram is to be interpreted in a dual sense in terms of its action on the universe and of its action on the world of men. In relation to the universe, the hexagram expresses the strong, creative action of the Deity. In relation to the human world, it denotes the creative action of the holy man or sage, of the ruler or leader of men, who through his power awakens and develops their higher nature.`,
        judgement:  `The Creative works sublime success, Furthering through perseverance.According to the original meaning, the attributes [sublimity, potentiality of success, power to further, perseverance] are paired. When an individual draws this oracle, it means that success will come to him from the primal depths of the universe and that everything depends upon his seeking his happiness and that of others in one way only, that is, by perseverance in what is right. The specific meanings of the four attributes became the subject of speculation at an early date. The Chinese word here rendered by 'sublime' means literally 'head,' 'origin,' 'great.' This is why Confucius says in explaining it: 'Great indeed is the generating power of the Creative; all beings owe their beginning to it. This power permeates all heaven.' For this attribute inheres in the other three as well. The beginning of all things lies still in the beyond in the form of ideas that have yet to become real. But the Creative furthermore has power to lend form to these archetypes of ideas. This is indicated in the word success, and the process is represented by an image from nature: The clouds pass and the rain does its work, and all individual beings flow into their forms. Applies to the human world, these attributes show the great man the way to notable success: Because he sees with great clarity and cause and effects, he completes the six steps at the right time and mounts toward heaven on them at the right time, as though on six dragons. The six steps are the six different positions given in the hexagram, which are represented later by the dragon symbol. Here it is shown that the way to success lies in apprehending and giving actuality to the way of the universe [Tao], which, as a law running through end and beginning, brings about all phenomena in time. Thus each step attained forthwith becomes a preparation for the next. Time is no longer a hindrance but the means of making actual what is potential. The act of creation having found expression in the two attributes sublimity and success, the work of conservation is shown to be a continuous actualization and differentiation of form. This is expressed in the two terms 'furthering' (literally, 'creating that which accords with the nature of a given being') and 'persevering' (literally, 'correct and firm'). 'The course of the Creative alters and shapes beings until each attains its true, specific nature, then it keeps them in conformity with the Great Harmony. Thus does it show itself to further through perseverance.' In relation to the human sphere, this shows how the great man brings peace and security to the world through his activity in creating order: 'He towers high above the multitude of beings, and all lands are united in peace.' Another line of speculation goes still further in separating the words 'sublime,' 'success,' 'furthering,' 'perseverance,' and parallels them with the four cardinal virtues in humanity. To sublimity, which, as the fundamental principle, embraces all the other attributes, it links love. To the attribute success are linked the morals, which regulate and organize expressions of love and thereby make them successful. The attribute furthering is correlated with justice, which creates the conditions in which each receives that which accords with his being, that which is due him and which constitutes his happiness. The attribute perseverance is correlated with wisdom, which discerns the immutable laws of all that happens and can therefore bring about enduring conditions. These speculations, already broached in the commentary called Wên Yen , later formed the bridge connecting the philosophy of the five stages (elements) of change, as laid down in the Book of History (Shu Ching) with the philosophy of the Book of Changes, which is based solely on the polarity of positive and negative principles. In the course of time this combination of the two systems of thought opened the way for an increasingly intricate number symbolism.`,
        image:`The movement of heaven is full of power.Thus the superior man makes himself strong and untiring. Since there is only one heaven, the doubling of the trigram Ch'ien, of which heaven is the image, indicates the movement of heaven. One complete revolution of heaven makes a day, and the repetition of the trigram means that each day is followed by another. This creates the idea of time. Since it is the same heaven moving with untiring power, there is also created the idea of duration both in and beyond time, a movement that never stops nor slackens, just as one day follows another in an unending course. This duration in time is the image of the power inherent in the Creative. With this image as a model, the sage learns how best to develop himself so that his influence may endure. He must make himself strong in every way, by consciously casting out all that is inferior and degrading. Thus he attains that tirelessness which depends upon consciously limiting the fields of his activity.`,
        lines:`Nine in the second place means: 

        Dragon appearing in the field.
        It furthers one to see the great man.
        
        Here the effects of the light-giving power begin to manifest themselves. In terms of human affairs, this means that the great man makes his appearance in his chosen field of activity. As yet he has no commanding position but is still with his peers. However, what distinguishes him form the others is his seriousness of purpose, his unqualified reliability, and the influence he exerts on his environment with out conscious effort. Such a man is destined to gain great influence and to set the world in order. Therefore it is favorable to see him.
        
        Nine in the third place means:
        
        All day long the superior man is creatively active.
        At nightfall his mind is still beset with cares.
        Danger. No blame.
        
        A sphere of influence opens up for the great man. His fame begins to spread. The masses flock to him. His inner power is adequate to the increased outer activity. There are all sorts of things to be done, and when others are at rest in the evening, plans and anxieties press in upon him. But danger lurks here at the place of transition from lowliness to the heights. Many a great man has been ruined because the masses flocked to him and swept him into their course. Ambition has destroyed his integrity. However, true greatness is not impaired by temptations. He who remains in touch with the time that is dawning, and with its demands is prudent enough to avoid all pitfalls, and remains blameless.
        
        Nine in the fourth place means:
        
        Wavering flight over the depths.
        No blame.
        
        A place of transition has been reached, and free choice can enter in. A twofold possibility is presented to the great man: he can soar to the heights and play an important part in the world, or he can withdraw into solitude and develop himself. He can go the way of the hero or that of the holy sage who seeks seclusion. There is no general law of his being. If the individual acts consistently and is true to himself, he will find the way that is appropriate for him. This way is right for him and without blame.
        
        Nine in the fifth place means:
        
        Flying dragon in the heavens.
        It furthers one to see the great man.
        
        Here the great man has attained the sphere of the heavenly beings. His influence spreads and becomes visible throughout the whole world. Everyone who sees him may count himself blessed. Confucius says about this line:
        
        Things that accord in tone vibrate together. Things that have affinity in their inmost natures seek one another. Water flows to what is wet, fire turns to what is dry. Clouds (the breath of heaven) follow the dragon, wind (the breath of earth) follows the tiger. Thus the sage arises, and all creatures follow him with their eyes. What is born of heaven feels related to what is above. What is born of earth feels related to what is below. Each follows its kind.
        
        Nine at the top means:
        
        Arrogant dragon will have cause to repent.
        
        When a man seeks to climb so high that he loses touch with the rest of mankind, he becomes isolated, and this necessarily leads to failure. This line warns against titanic aspirations that exceed one's power. A precipitous fall would follow.
        When all the lines are nines, it means:
        
        There appears a flight of dragons without heads.
        Good fortune.
        
        When all the lines are nines, it means that the whole hexagram is in motion and changes into the hexagram K'un, THE RECEPTIVE, whose character is devotion. The strength of the Creative and the mildness of the Receptive unite. Strength is indicated by the flight of dragons, mildness by the fact that their heads are hidden. This means that mildness in action joined to strength of decision brings good fortune.`
    },
}

const seq_GreyCode = [
    2,24,19,7,46,11,36,15,
    62,55,34,32,40,54,51,16,
    45,17,58,47,28,43,49,31,
    39,63,5,48,29,60,3,8,
    20,42,61,59,57,9,37,53,
    33,13,1,44,6,10,25,12,
    35,21,38,64,50,14,30,56,
    52,22,26,18,4,41,27,23
    ];

function getHexagramByBinary(binary)
{
    let hexagram = this.sequence_binary().filter((item) => item.binary == binary);
    if (hexagram.length > 0)
    {
        return this.sequence_binary().filter((item) => item.binary == binary)[0];
    }
    else return this.hexagram.kūn;
   
}
 function sequence_kingwen()
 {
    return _.sortBy(hexagram, ['kingwen'],['asc']);
 }

 function sequence_binary()
 {
    return _.sortBy(hexagram, ['order'],['asc']);
 }
 function sequence_greycode()
 {
    let start = sequence_kingwen();
    let sequence_GreyCode = [];

    for (let i = 0; i <= start.length-1; i++)
    {     
        sequence_GreyCode.push(start[seq_GreyCode[i]-1]);
    }
    
    return sequence_GreyCode;
 }

 function getHexagramByAboveBelow(above, below)
 {
    let hexagram = this.sequence_kingwen().filter((item) => item.above == above && item.below == below);
    if (hexagram.length > 0)
    {
        return hexagram[0];
    }
    else return this.hexagram.kūn;
 }



export default
{
    hexagram,
    getHexagramByBinary,
    sequence_binary,
    sequence_kingwen,
    sequence_greycode,
    getHexagramByAboveBelow,

}